### ISSUE TITLE
Endpoint Request

### ISSUE THREAD

**Issue by vinayentc** [awslabs/visual-search#3]
Can you kindly provide the example sagemaker API request which we can make from the Postman.

Below part of code do makes the definitions of the same -

from sagemaker.predictor import csv_serializer, json_deserializer
knn_predictor.content_type = 'text/csv'
knn_predictor.accept = 'application/json; verbose=true'
knn_predictor.serializer = csv_serializer
knn_predictor.deserializer = json_deserializer

**Comment by rabowskyb** [comment]
Hello, at this time we do not have a specific example of using Postman in this way.  As a starting point, you might look at this from the AWS documentation:  https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-use-postman-to-call-api.html.
