### ISSUE TITLE
Example Request

### ISSUE THREAD

**Issue by vinayentc** [awslabs/visual-search#4]
Can you please elaborate and provide an example request for the below lines from the blog -

"Although the Predictor object we created above could convert the raw Numpy ndarray feature vector to RecordIO-protobuf format, we'll ask it to use CSV. This might be helpful, for example, if your underlying application sends the feature vector as a CSV string."

**Comment by rabowskyb** [comment]
The only example request provided in this repo is in the sample notebook at https://github.com/awslabs/visual-search/blob/master/notebooks/visual-search-feature-generation.ipynb.  For further details about the Predictor object and serialization features, a starting point is the SDK documentation at https://sagemaker.readthedocs.io/en/stable/predictors.html.
